var classify = [{
	"id": 1,
	"name": "在线转换",
	"list": [{
		"name": "Sass/Less/Stylus在线转换工具",
		"url": "/tool/csass",
		"hot": 0,
		"img": ""
	}, {
		"name": "RGB/RGBA/HEX/HSL/HSV颜色在线转换工具",
		"url": "/tool/color",
		"hot": 0,
		"img": ""
	}, {
		"name": "免费快速将视频转换成Gif",
		"url": "/tool/giftxt",
		"hot": 1,
		"img": ""
	}, {
		"name": "Html/MarkDown在线互转工具",
		"url": "/tool/htmarkdown",
		"hot": 0,
		"img": ""
	}, {
		"name": "JSON/YAML在线转换",
		"url": "/tool/jsonyaml",
		"hot": 1,
		"img": ""
	}, {
		"name": "下载链接转换",
		"url": "/php/changeurl",
		"hot": 0,
		"img": ""
	}, {
		"name": "SVG转PNG工具",
		"url": "/tool/svg2img",
		"hot": 0,
		"img": ""
	}, {
		"name": "文本替换工具",
		"url": "/tool/textreplace",
		"hot": 0,
		"img": ""
	}, {
		"name": "度量衡单位在线换算工具",
		"url": "/tool/unitable",
		"hot": 0,
		"img": ""
	}, {
		"name": "json转Excel/csv工具",
		"url": "/tool/jsonscv",
		"hot": 0,
		"img": ""
	}, {
		"name": "时间戳转换_在线时间单位转换器",
		"url": "/tool/etc/#?id=4",
		"hot": 0,
		"img": ""
	}, {
		"name": "在线url网址编码、解码",
		"url": "/tool/etc/#?id=3",
		"hot": 1,
		"img": ""
	}, {
		"name": "地理坐标转换工具",
		"url": "/tool/coordinate",
		"hot": 0,
		"img": ""
	}, {
		"name": "Htaccess在线转换nginx",
		"url": "/tool/htaccess2nginx",
		"hot": 0,
		"img": ""
	}, {
		"name": "进制转换工具",
		"url": "/tool/radix",
		"hot": 0,
		"img": ""
	}, {
		"name": "人民币大写转换工具",
		"url": "/tool/renmingbi",
		"hot": 1,
		"img": ""
	}, {
		"name": "中文/Unicode在线转换",
		"url": "/tool/unicode",
		"hot": 0,
		"img": ""
	}, {
		"name": "在线中文汉字转换拼音工具",
		"url": "/tool/pinyin",
		"hot": 0,
		"img": ""
	}, {
		"name": "简体/繁体字转换",
		"url": "/tool/fantizi",
		"hot": 0,
		"img": ""
	}, {
		"name": "ASCII字符艺术生成器",
		"url": "/tool/taag",
		"hot": 0,
		"img": ""
	}, {
		"name": "json转golang struct对象",
		"url": "/tool/json2go",
		"hot": 0,
		"img": ""
	}, {
		"name": "英文字母大小写/空格/下划线/驼峰等转换工具",
		"url": "/tool/daxiaoxie",
		"hot": 0,
		"img": ""
	}, {
		"name": "XML转JSON、JSON转XML工具",
		"url": "/tool/xml2json",
		"hot": 1,
		"img": ""
	}]
}, {
	"id": 2,
	"name": "加密解密",
	"list": [{
		"name": "在线加密解密【Base64、AES、DES】",
		"url": "/tool/cipher",
		"hot": 1,
		"img": ""
	}, {
		"name": "Js加密混淆/压缩工具",
		"url": "/tool/jsblur",
		"hot": 1,
		"img": ""
	}, {
		"name": "文本隐藏加密工具",
		"url": "/tool/txtencrypt",
		"hot": 0,
		"img": ""
	}, {
		"name": "DES在线加密解密",
		"url": "/tool/des",
		"hot": 0,
		"img": ""
	}, {
		"name": "md5在线加密工具",
		"url": "/tool/md5",
		"hot": 0,
		"img": ""
	}, {
		"name": "随机密码生成工具",
		"url": "/tool/password",
		"hot": 0,
		"img": ""
	}, {
		"name": "摩斯电码翻译器_摩斯电码编码解码",
		"url": "/tool/morse",
		"hot": 0,
		"img": ""
	}, {
		"name": "URL网址16进制加密工具",
		"url": "/tool/urlcode",
		"hot": 0,
		"img": ""
	}, {
		"name": "在线编码转换工具",
		"url": "/tool/transcoding",
		"hot": 0,
		"img": ""
	}, {
		"name": "Escape加密/解密",
		"url": "/tool/escape",
		"hot": 0,
		"img": ""
	}, {
		"name": "密码安全性在线检测",
		"url": "/tool/passafe",
		"hot": 0,
		"img": ""
	}]
}, {
	"id": 3,
	"name": "站长工具",
	"list": [{
		"name": "免费在线智能AI文章伪原创工具",
		"url": "/php/weiyuanchuang",
		"hot": 1,
		"img": ""
	}, {
		"name": "AI提示词常用指令",
		"url": "/tool/aishort",
		"hot": 1,
		"img": ""
	},{
		"name": "Markdown在线编辑器",
		"url": "/tool/markdown",
		"hot": 0,
		"img": ""
	}, {
		"name": "站长常用转换工具【编码解码】",
		"url": "/tool/etc",
		"hot": 1,
		"img": ""
	}, {
		"name": "Markdown微信公众号排版编辑器",
		"url": "/tool/weixinmd",
		"hot": 1,
		"img": ""
	}, {
		"name": "域名/IP地址查询",
		"url": "/php/ipquery",
		"hot": 0,
		"img": ""
	}, {
		"name": "自适应网页多端预览工具",
		"url": "/tool/preview",
		"hot": 0,
		"img": ""
	}, {
		"name": "meta标签在线生成工具",
		"url": "/tool/meta",
		"hot": 0,
		"img": ""
	}, {
		"name": "电子邮箱网址大全",
		"url": "/tool/email",
		"hot": 0,
		"img": ""
	}, {
		"name": "免费短链接生成工具",
		"url": "/php/shorturl",
		"hot": 0,
		"img": ""
	}, {
		"name": "Robots文件生成器",
		"url": "/tool/robots",
		"hot": 0,
		"img": ""
	}, {
		"name": "域名whois查询",
		"url": "/php/whois",
		"hot": 0,
		"img": ""
	}, {
		"name": "邮件群发营销工具",
		"url": "/php/mailer",
		"hot": 0,
		"img": ""
	}, {
		"name": "在线html/js/css标签过滤工具",
		"url": "/tool/clearhtm",
		"hot": 0,
		"img": ""
	}, {
		"name": "ICP备案查询_网站域名备案查询",
		"url": "/php/icp",
		"hot": 0,
		"img": ""
	}, {
		"name": "浏览器内核版本检测器_查看userAgent信息",
		"url": "/php/useragent",
		"hot": 0,
		"img": ""
	}, {
		"name": "网站301转向/跳转代码生成工具",
		"url": "/tool/redirect",
		"hot": 0,
		"img": ""
	}, {
		"name": "今日热榜_实时新闻分享",
		"url": "/php/hotnews",
		"hot": 0,
		"img": ""
	}, {
		"name": "m3u8视频在线提取工具",
		"url": "/tool/m3u8",
		"hot": 0,
		"img": ""
	}, {
        "name":"微信域名拦截检测",
        "url":"https://www.fly63.com/php/wxCheck",
        "hot": 0,
		"img": ""
    }, {
        "name":"PDF文字识别",
        "url":"https://www.fly63.com/tool/pdfdraw",
        "hot": 0,
		"img": ""
    }, {
        "name":"敏感词/违禁词检测",
        "url":"https://www.fly63.com/tool/textcensoring",
        "hot": 1,
		"img": ""
    }]
}, {
	"id": 4,
	"name": "代码开发",
	"list": [{
		"name": "代码在线编辑器IDE",
		"url": "/tool/editoronline",
		"hot": 1,
		"img": ""
	}, {
		"name": "在线js代码生成工具",
		"url": "/tool/code",
		"hot": 0,
		"img": ""
	}, {
		"name": "HTTP在线模拟测试工具",
		"url": "/php/http",
		"hot": 1,
		"img": ""
	}, {
		"name": "Diff在线文本比较工具",
		"url": "/tool/textdiff",
		"hot": 1,
		"img": ""
	}, {
		"name": "html转js在线工具",
		"url": "/tool/html2js",
		"hot": 0,
		"img": ""
	}, {
		"name": "uuid在线生成器",
		"url": "/tool/uuid",
		"hot": 1,
		"img": ""
	}, {
		"name": "curl命令转代码",
		"url": "/tool/curl2code",
		"hot": 0,
		"img": ""
	}, {
		"name": "sql格式化",
		"url": "/tool/sqlformat",
		"hot": 0,
		"img": ""
	}, {
		"name": "网页数据采集抓取",
		"url": "/php/crawl",
		"hot": 0,
		"img": ""
	}, {
		"name": "JSON在线解析工具",
		"url": "/tool/JsonFormat",
		"hot": 1,
		"img": ""
	}, {
		"name": "JSON生成JavaBean、C#实体类",
		"url": "/tool/JsonToModel",
		"hot": 0,
		"img": ""
	}, {
		"name": "代码转图片_高雅程序员必备工具",
		"url": "/tool/code2img",
		"hot": 0,
		"img": ""
	}, {
		"name": "sql在线数据库设计工具",
		"url": "/tool/sqldesigner",
		"hot": 0,
		"img": ""
	}, {
		"name": "Element表单代码生成器",
		"url": "/tool/element-form",
		"hot": 0,
		"img": ""
	}, {
		"name": "Javascript或HTML在线美化，格式化",
		"url": "/tool/beautify",
		"hot": 0,
		"img": ""
	}, {
		"name": "正则表达式调试工具",
		"url": "/tool/regex",
		"hot": 1,
		"img": ""
	}, {
		"name": "正则表达式在线测试工具",
		"url": "/tool/regextest",
		"hot": 0,
		"img": ""
	}, {
		"name": "HTML/CSS/Javascript在线代码运行工具",
		"url": "/tool/runcode",
		"hot": 0,
		"img": ""
	}, {
		"name": "JSON格式化及高亮",
		"url": "/tool/jon",
		"hot": 0,
		"img": ""
	}, {
		"name": "HTML在线压缩工具",
		"url": "/tool/htmcpr",
		"hot": 0,
		"img": ""
	}, {
		"name": "Linux常用命令查询工具",
		"url": "/tool/linux",
		"hot": 1,
		"img": ""
	}, {
		"name": "Crontab表达式在线生成器",
		"url": "/tool/crontab",
		"hot": 0,
		"img": ""
	}, {
		"name": "VIM编辑器模拟_vim命令学习工具",
		"url": "/tool/vim",
		"hot": 0,
		"img": ""
	}, {
		"name": "程序员代码变量命名工具",
		"url": "/php/codevar",
		"hot": 1,
		"img": ""
	}, {
		"name": "275个简洁1行Js代码片段",
		"url": "/tool/1loc",
		"hot": 0,
		"img": ""
	}]
}, {
	"id": 5,
	"name": "Css样式",
	"list": [{
		"name": "CSS三角形生成器",
		"url": "/tool/cstriangle",
		"hot": 0,
		"img": ""
	}, {
		"name": "cssSprite/精灵图/雪碧图样式生成工具",
		"url": "/tool/sprite",
		"hot": 0,
		"img": ""
	}, {
		"name": "一个在线的路径裁剪工具",
		"url": "/tool/clippath",
		"hot": 0,
		"img": ""
	}, {
		"name": "在线生成字体CSS样式工具",
		"url": "/tool/cstxt",
		"hot": 0,
		"img": ""
	}, {
		"name": "CSS渐变色生成器",
		"url": "/tool/gradient",
		"hot": 1,
		"img": ""
	}, {
		"name": "SVG图形路径变形工具",
		"url": "/tool/svgchange",
		"hot": 0,
		"img": ""
	}, {
		"name": "CSS选择器演示 ",
		"url": "/tool/cssel/#debug",
		"hot": 0,
		"img": ""
	}, {
		"name": "CSS3在线样式生成器",
		"url": "/tool/cs3",
		"hot": 0,
		"img": ""
	}, {
		"name": "CSS新拟态设计风格生成器【Neumorphism】",
		"url": "/tool/neumorphism",
		"hot": 1,
		"img": ""
	}, {
		"name": "Css玻璃拟物化风格生成器【Glassmorphism】",
		"url": "/tool/glassmorphism",
		"hot": 1,
		"img": ""
	}, {
		"name": "CSS3 Flexbox 在线演示",
		"url": "/tool/flexbox",
		"hot": 0,
		"img": ""
	}, {
		"name": "CSS代码美化工具",
		"url": "/tool/cs",
		"hot": 0,
		"img": ""
	}, {
		"name": "网页颜色在线取色器",
		"url": "/tool/rgbcolor",
		"hot": 0,
		"img": ""
	}, {
		"name": "HTML5 标签含义之元素周期表",
		"url": "/tool/html5",
		"hot": 0,
		"img": ""
	}, {
		"name": "Animate.css动画演示",
		"url": "/tool/animate",
		"hot": 1,
		"img": ""
	}, {
		"name": "CSS按钮生成器",
		"url": "/tool/csbtn",
		"hot": 0,
		"img": ""
	}, {
		"name": "漂亮的CSS box-shadow样式",
		"url": "/tool/shadow",
		"hot": 0,
		"img": ""
	}, {
		"name": "web颜色搭配方案/设计网页配色表",
		"url": "/tool/colorMatch",
		"hot": 1,
		"img": ""
	}, {
		"name": "CSS在线压缩/格式化工具",
		"url": "/tool/csspack",
		"hot": 0,
		"img": ""
	}, {
		"name": "css loading炫酷的加载动画",
		"url": "/tool/loading",
		"hot": 1,
		"img": ""
	}, {
		"name": "CSS分割线在线制作",
		"url": "/tool/cssplit",
		"hot": 0,
		"img": ""
	}]
}, {
	"id": 6,
	"name": "二维码",
	"list": [{
		"name": "微信小程序二维码生成工具",
		"url": "/php/wxerm",
		"hot": 0,
		"img": ""
	}, {
		"name": "WIFI二维码生成器",
		"url": "/tool/wifiewm",
		"hot": 0,
		"img": ""
	}, {
		"name": "二维码在线生成器",
		"url": "/tool/ewm",
		"hot": 1,
		"img": ""
	}, {
		"name": "二维码在线解码工具",
		"url": "/php/decoder",
		"hot": 1,
		"img": ""
	}, {
		"name": "条形码生成器",
		"url": "/php/barcode",
		"hot": 0,
		"img": ""
	}, {
		"name": "支付宝微信收款码二合一",
		"url": "/tool/alipay",
		"hot": 0,
		"img": ""
	}]
}, {
	"id": 7,
	"name": "图片相关",
	"list": [{
		"name": "图片在线转换Base64数据",
		"url": "/tool/base64",
		"hot": 0,
		"img": ""
	}, {
		"name": "图片格式webp/png/jpeg转换工具",
		"url": "/tool/imgformat",
		"hot": 1,
		"img": ""
	}, {
		"name": "PDF文件转换图片工具",
		"url": "/tool/pdf2img",
		"hot": 0,
		"img": ""
	}, {
		"name": "在线将图片生成ascii字符画",
		"url": "/tool/img2char",
		"hot": 0,
		"img": ""
	}, {
		"name": "图片主色调在线获取工具",
		"url": "/tool/imagecolor",
		"hot": 0,
		"img": ""
	}, {
		"name": "占位图在线生成",
		"url": "/tool/bitmap",
		"hot": 0,
		"img": ""
	}, {
		"name": "图片在线压缩工具",
		"url": "/tool/picys",
		"hot": 0,
		"img": ""
	}, {
		"name": "图片在线生成ICO图标",
		"url": "/php/ico",
		"hot": 1,
		"img": ""
	}, {
		"name": "在线思维导图",
		"url": "/tool/rmind",
		"hot": 1,
		"img": ""
	}, {
		"name": "在线图片裁剪/生成",
		"url": "/tool/imgcut",
		"hot": 0,
		"img": ""
	}, {
		"name": "SVG在线编辑器",
		"url": "/tool/svgeditor",
		"hot": 0,
		"img": ""
	}, {
		"name": "图片加水印工具",
		"url": "/tool/watermark",
		"hot": 1,
		"img": ""
	}, {
		"name": "在线生成流程图、时序图工具",
		"url": "/tool/drawsvg",
		"hot": 1,
		"img": ""
	}, {
		"name": "画图工具_流程图、标注图、矢量图",
		"url": "/tool/diagram_sfd",
		"hot": 1,
		"img": ""
	}, {
		"name": "在线视频截图",
		"url": "/tool/videoposter",
		"hot": 1,
		"img": ""
	}, {
		"name": "图片合成工具_头像加圣诞帽、口罩",
		"url": "/tool/avatar",
		"hot": 0,
		"img": ""
	}, {
		"name": "生成九宫格图片",
		"url": "/tool/jiugongge",
		"hot": 0,
		"img": ""
	}, {
		"name": "Gif图片分解成序列帧",
		"url": "/tool/gifres",
		"hot": 0,
		"img": ""
	}, {
		"name": "照片加滤镜特效",
		"url": "/tool/imgfilter",
		"hot": 0,
		"img": ""
	}, {
		"name": "图片编辑工具",
		"url": "/tool/imgedit",
		"hot": 0,
		"img": ""
	}, {
		"name": "网页地址栏favicon图标制作",
		"url": "/tool/favicon",
		"hot": 0,
		"img": ""
	}, {
		"name": "在线画桌白板工具",
		"url": "/tool/whiteboard",
		"hot": 0,
		"img": ""
	}, {
        "name":"像素画板工具",
        "url":"/tool/pixeldraw",
        "hot": 0,
		"img": ""
    }]
}, {
	"id": 8,
	"name": "生活工具",
	"list": [{
		"name": "公历农历转换查询工具",
		"url": "/tool/calendar",
		"hot": 0,
		"img": ""
	}, {
		"name": "手机号码归属地查询",
		"url": "/php/mobile",
		"hot": 0,
		"img": ""
	}, {
		"name": "中国亲戚关系计算器",
		"url": "/tool/relationship",
		"hot": 0,
		"img": ""
	}, {
		"name": "世界各国区号时差查询",
		"url": "/tool/areacode",
		"hot": 0,
		"img": ""
	}, {
		"name": "在线年龄计算器",
		"url": "/tool/nianling",
		"hot": 0,
		"img": ""
	}, {
		"name": "年化收益计算器",
		"url": "/tool/nianlvli",
		"hot": 0,
		"img": ""
	}, {
		"name": "淘宝/天猫超市优惠券",
		"url": "http://tb.fly63.com",
		"hot": 1,
		"img": ""
	}, {
		"name": "房贷计算器",
		"url": "/tool/fangdai",
		"hot": 0,
		"img": ""
	}, {
		"name": "心理测试工具",
		"url": "/tool/test",
		"hot": 1,
		"img": ""
	}, {
		"name": "在线图表工具_饼状/折线/柱状/漏斗/雷达图",
		"url": "/tool/chart",
		"hot": 1,
		"img": ""
	}, {
		"name": "化学元素周期表查询工具",
		"url": "/tool/yuansu",
		"hot": 0,
		"img": ""
	}, {
		"name": "个人所得税计算器",
		"url": "/tool/gerenshui",
		"hot": 1,
		"img": ""
	}, {
		"name": "复利计算器_复利增值在线计算",
		"url": "/tool/fuli",
		"hot": 0,
		"img": ""
	}, {
		"name": "周公解梦查询大全",
		"url": "/tool/dream",
		"hot": 0,
		"img": ""
	}, {
		"name": "花语大全 - 查询各种花的花语",
		"url": "/tool/huayu",
		"hot": 0,
		"img": ""
	}, {
		"name": "天数间隔计算器",
		"url": "/tool/day",
		"hot": 0,
		"img": ""
	}, {
		"name": "生活垃圾分类查询",
		"url": "/tool/garbage",
		"hot": 0,
		"img": ""
	}, {
		"name": "古诗词在线起名/取名",
		"url": "/tool/qiming",
		"hot": 1,
		"img": ""
	}, {
		"name": "国内邮政编码大全",
		"url": "/tool/zipcode",
		"hot": 0,
		"img": ""
	}, {
		"name": "世界各地时间转换查询工具",
		"url": "/tool/worldtime",
		"hot": 1,
		"img": ""
	}, {
		"name": "百家姓排名查询大全",
		"url": "/tool/bjx",
		"hot": 0,
		"img": ""
	}, {
		"name": "弟子规全文及解释",
		"url": "/tool/dzg",
		"hot": 0,
		"img": ""
	}, {
		"name": "银行卡号归属地查询",
		"url": "/tool/bankinfo",
		"hot": 1,
		"img": ""
	}, {
		"name": "国内车牌号码归属地查询",
		"url": "/tool/chepai",
		"hot": 0,
		"img": ""
	}, {
		"name": "在线秒表记时器",
		"url": "/tool/miaobiao",
		"hot": 0,
		"img": ""
	}, {
		"name": "子女血型遗存查询",
		"url": "/tool/xuexing",
		"hot": 0,
		"img": ""
	}, {
		"name": "服装尺寸对照表",
		"url": "/tool/size",
		"hot": 0,
		"img": ""
	}, {
		"name": "老黄历查询（吉日/星宿/时辰）",
		"url": "/tool/laohuangli",
		"hot": 0,
		"img": ""
	}, {
		"name": "白噪音,聆听大自然的声音",
		"url": "/tool/relax",
		"hot": 0,
		"img": ""
	}, {
        "name":"lrc歌词在线编辑工具",
        "url":"https://www.fly63.com/tool/lrc_editor",
        "hot": 0,
		"img": ""
    }, {
        "name":"食物嘌呤查询_痛风及高尿酸血症饮食表",
        "url":"https://www.fly63.com/tool/purine",
        "hot": 1,
		"img": ""
    }, {
        "name":"食物营养成分查询",
        "url":"https://www.fly63.com/tool/food",
        "hot": 0,
		"img": ""
    }, {
        "name":"饮水量计算器_每日喝水量",
        "url":"https://www.fly63.com/tool/heshui",
        "hot": 0,
		"img": ""
    }, {
        "name":"照片转像素风格画",
        "url":"https://www.fly63.com/tool/pixelit",
        "hot": 0,
		"img": ""
    }, {
        "name":"常用电话号码大全",
        "url":"https://www.fly63.com/tool/phone",
        "hot": 1,
		"img": ""
    }, {
        "name":"番茄钟计时器_效率工具",
        "url":"https://www.fly63.com/tool/tomato",
        "hot": 0,
		"img": ""
    }, {
        "name":"抛硬币做决定",
        "url":"https://www.fly63.com/tool/coin",
        "hot": 0,
		"img": ""
    }]
}, {
	"id": 9,
	"name": "娱乐工具",
	"list": [{
		"name": "毒鸡汤语录",
		"url": "/php/dujitang",
		"hot": 0,
		"img": ""
	}, {
		"name": "经典句子语录大全",
		"url": "/php/juzi",
		"hot": 1,
		"img": ""
	}, {
		"name": "微信翅膀昵称生成器",
		"url": "/tool/wing",
		"hot": 0,
		"img": ""
	}, {
		"name": "微信整蛊生成器",
		"url": "/tool/wxCreate",
		"hot": 0,
		"img": ""
	}, {
		"name": "历史上的今天",
		"url": "/php/todayHistory",
		"hot": 0,
		"img": ""
	}, {
		"name": "今天吃什么？",
		"url": "/tool/chi",
		"hot": 0,
		"img": ""
	}, {
		"name": "常用表情包大全",
		"url": "/php/emojiPkg",
		"hot": 0,
		"img": ""
	}, {
		"name": "在线网页小游戏_上班无聊摸鱼",
		"url": "/tool/game",
		"hot": 0,
		"img": ""
	}, {
		"name": "计算多少天后啪啪啪",
		"url": "/tool/papapa",
		"hot": 1,
		"img": ""
	}, {
		"name": "成语接龙查询器",
		"url": "/tool/cyjl",
		"hot": 0,
		"img": ""
	}, {
		"name": "歇后语查询工具",
		"url": "/tool/xiehouyu",
		"hot": 0,
		"img": ""
	}, {
		"name": "民间谚语在线查询",
		"url": "/tool/yanyu",
		"hot": 0,
		"img": ""
	}, {
		"name": "脑筋急转弯在线查询",
		"url": "/tool/naojin",
		"hot": 0,
		"img": ""
	}, {
		"name": "土味情话查询生成器",
		"url": "/tool/love",
		"hot": 0,
		"img": ""
	}, {
		"name": "绕口令大全",
		"url": "/tool/rkl",
		"hot": 0,
		"img": ""
	}, {
		"name": "笑话大全",
		"url": "/tool/joke",
		"hot": 0,
		"img": ""
	}, {
		"name": "狗屁不通文章生成器",
		"url": "/tool/bullshitGenerator",
		"hot": 1,
		"img": ""
	}, {
		"name": "彩虹屁文章生成器",
		"url": "/tool/rainbowfart",
		"hot": 1,
		"img": ""
	}, {
		"name": "每日一首古诗词",
		"url": "/php/poetry",
		"hot": 0,
		"img": ""
	}, {
		"name": "好玩的IOS优质App推荐",
		"url": "/tool/app",
		"hot": 0,
		"img": ""
	}, {
		"name": "谷歌吉他在线版",
		"url": "/tool/guitar",
		"hot": 0,
		"img": ""
	},{
		"name": "舔狗日记",
		"url": "/php/wedog",
		"hot": 0,
		"img": ""
	}, {
		"name": "彩虹屁文案语录",
		"url": "/php/caihongpi",
		"hot": 0,
		"img": ""
	}]
}, {
	"id": 10,
	"name": "文档手册",
	"list": [{
		"name": "ECMAScript 6入门",
		"url": "/tool/es6",
		"hot": 0,
		"img": ""
	}, {
		"name": "npm 中文文档 ",
		"url": "/tool/npmdoc",
		"hot": 0,
		"img": ""
	}, {
		"name": "Node.js中文文档",
		"url": "/tool/nodedoc",
		"hot": 0,
		"img": ""
	}, {
		"name": "中文技术文档写作规范",
		"url": "/tool/normdoc",
		"hot": 0,
		"img": ""
	}, {
		"name": "layui镜像文档",
		"url": "/manual/layui/web",
		"hot": 0,
		"img": ""
	}, {
		"name": "css在线参考手册",
		"url": "/manual/cs",
		"hot": 0,
		"img": ""
	}, {
		"name": "Jquery在线参考手册",
		"url": "/manual/jquery",
		"hot": 0,
		"img": ""
	}, {
		"name": "JavaScript在线参考手册",
		"url": "/manual/JavaScript",
		"hot": 0,
		"img": ""
	}, {
		"name": "React.js 中文参考文档",
		"url": "/tool/rectdoc",
		"hot": 0,
		"img": ""
	}, {
		"name": "Nginx中文文档",
		"url": "/tool/nginxdoc",
		"hot": 0,
		"img": ""
	}]
}, {
	"id": 11,
	"name": "其他工具",
	"list": [{
		"name": "在线文本去重复工具",
		"url": "/tool/quchong",
		"hot": 0,
		"img": ""
	}, {
		"name": "ASCII码对照表",
		"url": "/tool/ascii",
		"hot": 0,
		"img": ""
	}, {
		"name": "常用对照表",
		"url": "/tool/table",
		"hot": 1,
		"img": ""
	}, {
		"name": "域名分类大全、顶级域名后缀查询",
		"url": "/tool/domain",
		"hot": 0,
		"img": ""
	}, {
		"name": "字帖生成器",
		"url": "/tool/zitie",
		"hot": 0,
		"img": ""
	}, {
		"name": "字数统计工具",
		"url": "/tool/zishutongji",
		"hot": 0,
		"img": ""
	}, {
		"name": "文件格式/类型识别工具",
		"url": "/tool/filetype",
		"hot": 0,
		"img": ""
	}, {
		"name": "在线中文拆字解字",
		"url": "/tool/chaizi",
		"hot": 0,
		"img": ""
	}, {
		"name": "中英混排文档在线排版工具",
		"url": "/tool/text-ench",
		"hot": 0,
		"img": ""
	}, {
		"name": "网址导航，上网从这里开始",
		"url": "/tool/dao",
		"hot": 0,
		"img": ""
	}, {
		"name": "在线排版工具",
		"url": "/tool/paiban",
		"hot": 0,
		"img": ""
	}, {
		"name": "科学计算器",
		"url": "/tool/jisuanqi",
		"hot": 0,
		"img": ""
	}, {
		"name": "简约导航",
		"url": "http://hao.fly63.com",
		"hot": 1,
		"img": ""
	}, {
		"name": "数独题目生成器",
		"url": "/tool/sudoku",
		"hot": 0,
		"img": ""
	}, {
		"name": "24点计算器_在线24点解法器",
		"url": "/tool/24dian",
		"hot": 0,
		"img": ""
	}, {
		"name": "汉语字典_在线汉字查询",
		"url": "/tool/zidian",
		"hot": 0,
		"img": ""
	}, {
		"name": "成语词典",
		"url": "/tool/chengyu",
		"hot": 0,
		"img": ""
	}, {
		"name": "在线音频编辑器_Audio Editor",
		"url": "/tool/audioedit",
		"hot": 0,
		"img": ""
	}, {
		"name": "在线高清录屏",
		"url": "/tool/screenRecord",
		"hot": 0,
		"img": ""
	}, {
		"name": "质数计算器_质数(素数)在线判断",
		"url": "/tool/prime",
		"hot": 0,
		"img": ""
	}, {
		"name": "随机数生成器_支持带小数点",
		"url": "/tool/random",
		"hot": 0,
		"img": ""
	}, {
		"name": "方差、标准差计算器",
		"url": "/tool/fangcha",
		"hot": 0,
		"img": ""
	}, {
		"name": "IP网络地址/子网掩码计算与转换工具",
		"url": "/tool/ipjisuan",
		"hot": 0,
		"img": ""
	}, {
		"name": "fooplot数学函数绘图器工具",
		"url": "/tool/fooplot",
		"hot": 0,
		"img": ""
	}, {
		"name": "三角函数计算器_弧度与度在线换算",
		"url": "/tool/sanjiaohanshu",
		"hot": 0,
		"img": ""
	}, {
		"name": "三角形角度计算器_周长/面积/内径/半径",
		"url": "/tool/sanjiaoxingjiaodu",
		"hot": 0,
		"img": ""
	}, {
		"name": "百分比在线计算器",
		"url": "/tool/baifenbi",
		"hot": 0,
		"img": ""
	}, {
		"name": "个性特殊符号大全",
		"url": "/tool/fuhao",
		"hot": 1,
		"img": ""
	}, {
		"name": "自然对数计算器",
		"url": "/tool/zrds",
		"hot": 0,
		"img": ""
	}, {
		"name": "程序员一站式导航",
		"url": "/tool/cxy",
		"hot": 0,
		"img": ""
	}, {
		"name": "汉语在线分词工具",
		"url": "/tool/segmentit",
		"hot": 0,
		"img": ""
	}, {
		"name": "神奇字体_怪异英文生成器",
		"url": "/tool/weirdfonts",
		"hot": 0,
		"img": ""
	}, {
		"name": "键盘键码keyCode对照表",
		"url": "/tool/keyboardcode",
		"hot": 0,
		"img": ""
	}, {
		"name": "世界各国首都中英文对照表",
		"url": "/tool/shoudu",
		"hot": 0,
		"img": ""
	}]
}, {
	"id": 12,
	"name": "优惠券领取",
	"list": [{
		"name": "阿里云优惠券",
		"url": "/nav/2907",
		"hot": 0,
		"img": ""
	}, {
		"name": "腾讯云优惠券",
		"url": "/nav/2908",
		"hot": 0,
		"img": ""
	}, {
		"name": "硅云服务器/虚拟主机",
		"url": "/nav/3219",
		"hot": 0,
		"img": ""
	}, {
		"name": "淘宝天猫优惠券",
		"url": "http://tb.fly63.com",
		"hot": 1,
		"img": ""
	}]
}]
